### ISSUE TITLE
Update GFX Texture references in leader maker and core-modifying

### ISSUE THREAD

**Issue by openly-retro** [openly-retro/stellaris-machine-robot-expansion#1]
**Problem**

In the various `.gui` files, there are references to texture files that aren't in the current version of Stellaris (3.10.*)

**Fixing this issue will involve:**

1. Identify which texture files are missing
2. Attempt to identify meaningful replacements

Even adding any substitute graphics that fit will work.

**Goal**

We don't want to see any "ERROR" renderings in the GUI.

**Comment by mehronkugler** [comment]
![image](https://github.com/mehronkugler/stellaris-machine-robot-expansion/assets/3236094/4dd4e55b-45e5-447a-8425-3c82ed360b04)

**Comment by mehronkugler** [comment]
![image](https://github.com/mehronkugler/stellaris-machine-robot-expansion/assets/3236094/9fcd3ba7-3a26-4e67-8d32-4c9ddc05e5e5)

looks like it may be due to a wrong icon reference

**Comment by openly-retro** [comment]
donezo
