### ISSUE TITLE
Fix leader-making effects and scripted things

### ISSUE THREAD

**Issue by openly-retro** [openly-retro/stellaris-machine-robot-expansion#2]
Lots of tech debt to work through:

- No 1:1 equivalent of 3.9 subclasses to 3.10. this probably broke a lot of mods
- need to add more GUI for 4 subclasses
- the leader-making gui has 4 sections: admiral, general, scholar, governor
-- but now there are 3 "classes" of leaders, each with 4 sub-classes
-- so do we duplicate the commander class area in favor of trying to re-use the admiral / general interfaces?
-- this will be us artificially separating the two ideas which are now baked into one military-type leader
-- interestingly, behind the scenes Paradox still has an "admiral" traits file and a "general" traits file. so it's easy to sort the traits out for each
- adding in mod support for all the new traits means adding a lot of repeated code
- icon BGs will need to be sourced and checked
- More stuff will be added to this

**Comment by mehronkugler** [comment]
Look where `xvcv_mdlc_leader_making_trait_pick_effect` is used. This sets country vars with the given classname and trait ID. It's also called with a trait ID where it's a subclass.

1. Update ALL country name vars to have updated leader class names in them
2. update all invocations of this effect to give the correct classes and trait names

Then check our var names in the GUI files

**Comment by openly-retro** [comment]
done https://github.com/openly-retro/stellaris-machine-robot-expansion/pull/59
